// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gucregjxcmrmqfaonzlb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1Y3JlZ2p4Y21ybXFmYW9uemxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1ODAwMjUsImV4cCI6MjA2NzE1NjAyNX0.epmM6fwv4_tkNm7ExKGQrkJt-70JW3SdNzVG8fX132Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});